package backend;

import java.io.*;
import java.util.List;

public class ObjectWriter {

    public void writeObject(List<String> asmCode, String outputPath) throws IOException {
        File file = new File(outputPath);
        file.getParentFile().mkdirs();

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            // Write header
            writer.write("; LOBJ v1.0 - Compiled Turtle Language Object File\n");
            writer.write("; Generated by Turtle Compiler\n");
            writer.write("\n");

            // Write instructions
            for (String line : asmCode) {
                writer.write(line);
                writer.write("\n");
            }
        }
    }

    public void writeAsm(List<String> asmCode, String outputPath) throws IOException {
        File file = new File(outputPath);
        file.getParentFile().mkdirs();

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            for (String line : asmCode) {
                writer.write(line);
                writer.write("\n");
            }
        }
    }

    public void writeIR(String irText, String outputPath) throws IOException {
        File file = new File(outputPath);
        file.getParentFile().mkdirs();

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(irText);
        }
    }
}

